### ISSUE TITLE
Error in informatica_roll_back_deployment.groovy

### ISSUE THREAD

**Issue by MatakuMike** [IBM-UrbanCode/Informatica-UCD#11]
The -n switch for the rollbackdeployment is incorrect and should be -t.  Please fix when you can as we have to modify this with every new version.

**Comment by nhmathis** [comment]
Feel free to submit a pull request with this change. 

Otherwise, we will get to it as soon as we can.

**Comment by nhmathis** [comment]
Documentation for reference: http://gerardnico.com/doc/powercenter/PC_861_CommandReference.pdf

**Comment by nhmathis** [comment]
Merged and released in [version 22](https://github.com/IBM-UrbanCode/Informatica-UCD/releases/tag/22).
