### ISSUE TITLE
Informatica PowerCenter vs PowerExchange

### ISSUE THREAD

**Issue by mbeshara** [IBM-UrbanCode/Informatica-UCD#12]
This plugin refers to Informatica PowerCenter. Does the plugin work with Informatica PowerExchange, or is there another plugin that does?

Thanks!

**Comment by nhmathis** [comment]
Hi @mbeshara,

The Informatica plugin takes advantage of the [pmrep command line interface](https://marketplace.informatica.com/solutions/pmrep_command_central) which is a PowerCenter tool.  This means that the the plugin must run on a PowerCenter server. However, the two products can be installed on the same server. 

Looking at PowerExchange documentation, it looks as it would use a different cli outlined [here](https://kb.informatica.com/proddocs/Product%20Documentation/4/PWX_100_CommandReference_en.pdf). We currently do not have a plugin that supports these PowerExchange commands.

-Nick

**Comment by mbeshara** [comment]
No problem, thanks!
