### ISSUE TITLE
Create Dynamic Deployment group: cannot run program "pmrep": error=2, No such file or directory "

### ISSUE THREAD

**Issue by kkp1225** [IBM-UrbanCode/Informatica-UCD#13]
Hi,

I'm testing this Informatica-UCD plugin v20.

I'm getting an error "cannot run program 'pmrep'" at step Create Dynamic Deployment. 

It could not find location of pmrep. Also I don't see an option to specify the INFA HOME(/opt/infa/9.6) location as we have in step "Validate Deployment Group".

How do I resolve this issue ? Please let me know.

Thanks,
Kiran

**Comment by nhmathis** [comment]
Hi,

The `pmrep` cli needs to be on the Environment Path variable. Since you are on Linux/UNIX, this would be set in your `.bashrc` or `.profile` and would be initialized on start up. 

Here is a quick doc on setting it in the `.profile`: http://datawarehouse.ittoolbox.com/groups/technical-functional/informatica-l/pmrep-command-not-found-when-executing-from-command-line-on-unix-box-4341367

- Nick

**Comment by kkp1225** [comment]
Thanks for your response Nick. Yes, We have tried adding environment variables to the .profile for the user which is running the UCD agent. No luck so far.

I was wondering, if we can populate INFA HOME property inside "Create Dynamic Deployment" like we have in step "Validate Deployment Group"

**Comment by nhmathis** [comment]
Yup, that's possible. If you want to make a pull request, you would pretty much replace [line 52](https://github.com/IBM-UrbanCode/Informatica-UCD/blob/master/src/main/scripts/create_dynamic_deployment.groovy#L52) with...

```
if (infaHome != null && infaHome != "") {
    command.add(infaHome + File.separator + "server" + File.separator + "bin" + File.separator + "pmrep");
    }
else {
        command.add('pmrep')
    }
```

Then add a new property to the `Create Dynamic Deployment` step in the plugin.xml, add the new property, and properly migrate the step and property in the upgrade.xml.

Feel free to make a pull request with these changes.

**Comment by kkp1225** [comment]
thanks for the updates Nick, I have made my changes and created the pull request. Please review it.

**Comment by nhmathis** [comment]
Merged #14 and #15 and releasing soon.

**Comment by nhmathis** [comment]
Note: The plugin's version has been bumped to 21

**Comment by nhmathis** [comment]
Released [version 21](https://github.com/IBM-UrbanCode/Informatica-UCD/releases/tag/21). Feel free to reopen if you have any problems.
