### ISSUE TITLE
Informatica urbandeploy plugin 14.0

### ISSUE THREAD

**Issue by prabhatofficial** [IBM-UrbanCode/Informatica-UCD#2]
We are facing issue with deployment of informatica plugin 14.0  
against urbandeploy server "6.1.1.3.653823".                            

while deploying file with complete batch the deployment exits in  
between, when deployed separately deployment works fine.    

Regards
prabhat

**Comment by nhmathis** [comment]
The step in question is "Import Objects". 

Hey @prabhatofficial,

This error is very unfortunate as it seems that there is no true error output or stack trace provided by Informatica or the plugin. In version 14, I've added a catch() block that should provide helpful output if the error was caused as a result of the plugin code. However, the lack of errors entirely indicates that the Informatica command canceled suddenly. 

I recommend making a small change to the plugin, running the new plugin, gathering the script files that are used to run the command, and then running the Informatica command manually. Through running manually, the Informatica command line may present additional error output that the plugin is missing.

1) Clone the repo locally (which is sounds like you have already done)
2) In "import_objects.groovy", comment out the lines:
    // script.delete() ->line 289
   and
   // it.delete() -> line 306
This will prevent the script and and import helper files from being removed after the step's completion. You can then use these exact files, and run the Informatica command manually. 
3) Build and install the plugin. Run the "Import Object" step.
4) Open the command prompt on the UrbanCode agent's machine and change directory into the working process's directory. You should find the script file (informatica_scipt.######.in) and the many other helper import files. 
5) Once in the correct directory, run the following command: 
"/opt/informatica/dev/10.1/server/bin/pmrep run -o manual_run.out -f <input_script> -e -s"
You'll need to replace the the <input_script> with the script.in file generated by the plugin. Once replaced, run the command. 
6) This is the exact command the plugin would be running. At this point, we should get additional information in the manual_run.out file on how the Informatica command ran. If we can't get this command running, then the plugin won't work either. This would point to it being an an Informatica issue. However, if it is working on the command line, then it would indicate a plugin issue. 

If there is additional error output after this manual run, feel free to post it here. 

Let me know if you have any other questions.
- Nick

**Comment by prabhatofficial** [comment]
Hi

It exits with below error

pcadmd91:/opt/urbandeploy-im/agent/var/work/ISFA RDS ETL AIX/DIT2/deploy_artifact[dev]>out -f informatica_script.1475644445137.in -e -s                             <
Informatica(r) PMREP, version [10.1.0], build [1205.0609], AIX 64-bit
Copyright (c) 1993-2016 Informatica LLC. All Rights Reserved.
See patents at https://www.informatica.com/legal/patents.html.

Invoked at Wed Oct 05 06:23:08 2016

Memory fault

Regards
Prabhat
The information transmitted is intended for the person or entity to which it is addressed and may contain confidential, privileged or copyrighted material or attorney work product. If you receive this in error, please contact the sender and delete the material from any system. Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden. Any comments or statements made are not necessarily those of Fidelity. All e-mails may be monitored or recorded.

**Comment by nhmathis** [comment]
It looks like the batch file that is generated by the plugin is too large. This would explain why running these deployments separately works, but fails when run together. The immediate work around is to run separately or only batch a few deployments together. (You'll have to find the 'just-right' amount that works for your scenario.) The second method should be faster than a sequential deployment, but will require a bit of trial and error. 

If this is truly an issue, you'll have to reach out to the Informatica and report an issue with their CLI.

**Comment by prabhatofficial** [comment]
HI

Informatica case is already raised and in progress, can you provide us a updated plugin which can create multiple batch input files with flexibility to choose the batch size as this issue is impacting lot of applications.

Regards
Prabhat
The information transmitted is intended for the person or entity to which it is addressed and may contain confidential, privileged or copyrighted material or attorney work product. If you receive this in error, please contact the sender and delete the material from any system. Any unauthorised copying, disclosure or distribution of the material in this e-mail is strictly forbidden. Any comments or statements made are not necessarily those of Fidelity. All e-mails may be monitored or recorded.

**Comment by nhmathis** [comment]
Hey @prabhatofficial,

The Informatica plugin is a community plugin. Therefore, the IBM UrbanCode team supports it on a best effort basis. Feel free to submit a pull request with the necessary changes. The Community Dev team will then work with you to merge your changes. 

If our team has the time to tackle this issue, could you please outline more of the requirements? What are you expecting by making the batch size configurable? Size of file or number of deployments? Would you prefer this to be managed under the covers and not be configurable? 

Do you have a work around in place? If so, what is it? 

Is the Informatica team working on a fix that will eliminate this issue?
