### ISSUE TITLE
control file "COPYDEPLOYMENTGROUP" NO

### ISSUE THREAD

**Issue by kkp1225** [IBM-UrbanCode/Informatica-UCD#24]
hi,

Im trying to deploy the deployment group, It is failing to copy few dependency workflows.

Looking at the control file output. I see.

COPYDEPLOYMENTGREOUP="NO"

Looking at the plugin step, I don't see a option to make this property "copydeploymentgroup" as YES.

Please review it and let me know the option for this.

Thanks,
Kiran

**Comment by nhmathis** [comment]
You are correct, this is not an option in the plugin step. It will always default to `No`. Fortunately, it would be a simple checkbox and a small logic change to make this functionality possible. Feel free to submit a pull request against the code with this change.

**Comment by kkp1225** [comment]
hi,

Is there any updates on this ? When we are promoting deployment group from DEV to SIT. It only coying the objects associated with the deployment group. But its not copying the deployment group. I see in the code it has default COPYDEPLOYMENTGREOUP="NO"

Can we make this YES to get this working ? Please let me know the options.

Thanks

**Comment by nhmathis** [comment]
Hi,

In the Deploy Deployment Group step, there is a hidden property called `Copy Deployment Group`. You'll want to select this checkbox to set the `COPYDEPLOYMENTGROUP` value to `YES`.
