### ISSUE TITLE
#informatica Apply Label process

### ISSUE THREAD

**Issue by vivekgite** [IBM-UrbanCode/Informatica-UCD#26]
Apply Label process step does not have a property security domain in the configuration(it is available for the steps Assign Permission and Import Objects).

Can some one help how do add the security domain to the apply label step

**Comment by nhmathis** [comment]
Enhancement request has been added in [release 25](https://github.com/IBM-UrbanCode/Informatica-UCD/releases/tag/25).

Thank you @daviddelapena!
