### ISSUE TITLE
PMREP character coding, UTF-8 vs ISO-8859-1

### ISSUE THREAD

**Issue by jsarnovsky** [IBM-UrbanCode/Informatica-UCD#3]
UrbanCode Deploy 6.2.1 
Informatica Plugin, Import Objects Version 15 
Description: PMREP's codepage not compatible with repo's code page. UTF- 8 encoding vs. ISO-8859-1 encoding. Before running the pmrep connect command, system is expecting the LANG variable to be set to ISO-8859-1. Changing either the ID encoding, or the Repository encoding not an option for us.

connect -r [repo] -n [userid] -s [security domain] -x [pass] -d [domain] 
 [[REP_61082] pmrep's code page (UTF-8 encoding of Unicode) is not one-way compatible to repository [repo]'s code page (ISO 8859-1 Western European).]
 [Failed to connect to repository service [repo].]
An error occurred while accessing the repository[Failed to connect to repository service [repo].]
 [11/30/2016 16:26:21-[REP_55102] Failed to connect to repository service [repo].]
Repository connection failed.
Failed to execute connect.

**Comment by nhmathis** [comment]
Issue has been resolved in version 17.
