### ISSUE TITLE
Security Domain Property not added

### ISSUE THREAD

**Issue by vivekgite** [IBM-UrbanCode/Informatica-UCD#33]
Security Domain property not available for below processes

Run PMREP Command
Create Static Deployment group
Create Dynamic Deployment group
Deploy Deployment group
Roll Back Deployment group

**Comment by nhmathis** [comment]
This feature has been added by @daviddelapena in v26 and has just been released:
[Informatica UCD v26](https://github.com/IBM-UrbanCode/Informatica-UCD/releases/tag/26)
