### ISSUE TITLE
When Importing multiple ImportObject, the program is terminating

### ISSUE THREAD

**Issue by leosraj** [IBM-UrbanCode/Informatica-UCD#36]
Core was generated by `/u01/app/Dev/Informatica/GALAXY_INFA_HOME/server/bin/pmrep run -o informatica_s'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f8c86743ddd in ExprSDKMgr::getFunction(unsigned short const*, unsigned short const*, ExprSDKFunc*&, PmUString&) () from /u01/app/Dev/Informatica/GALAXY_INFA_HOME/server/bin/libpmcmnrep.so
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.209.el6_9.2.x86_64 keyutils-libs-1.4-5.el6.x86_64 libgcc-4.4.7-18.el6.x86_64 libidn-1.18-2.el6.x86_64 libstdc++-4.4.7-18.el6.x86_64 nss-softokn-freebl-3.14.3-23.3.el6_8.x86_64

The solution we believe to be that if we remove pmrep run, and instead of having “ImportObject” in a script, calling it “pmrep ImportObject”, as well as any other pmrep command, that this would fix the issue

**Comment by nhmathis** [comment]
Are you receiving this issue through the plugin or manual calls? 

If via plugin, would you mind posting full logs?

If manually, please post the full command you are trying to run. Unless it's `/u01/app/Dev/Informatica/GALAXY_INFA_HOME/server/bin/pmrep run -o informatica_s`, which likely means you are missing the input file.

**Comment by leosraj** [comment]
Josh,

Can you please email the logs to Nick by responding to this email.



Thanks.



LEO J. SELVARAJ
IBM Certified IT Specialist – Level Two
IBM Systems Middleware Services


                                                                                     
                                                                                     
                                                                                     
                                                                                     
                                                                                     
                                                                                     
 2D barcode -  Phone: 1-720-395-1729 | Mobile: 1-248-837-9233                        
 encoded with  E-mail: leosraj@us.ibm.com                                            
 contact       ISSW:                                                                 
 information   www.ibm.com/developerworks/websphere/services/                        
                                                                                     
                                                                                     
                                                                                     








From:	Nick Mathison <notifications@github.com>
To:	IBM-UrbanCode/Informatica-UCD
            <Informatica-UCD@noreply.github.com>
Cc:	leosraj <leosraj@us.ibm.com>, Author
            <author@noreply.github.com>
Date:	12/06/2017 02:31 PM
Subject:	Re: [IBM-UrbanCode/Informatica-UCD] When Importing multiple
            ImportObject, the program is terminating (#36)





Are you receiving this issue through the plugin or manual calls?


If via plugin, would you mind posting full logs?


If manually, please post the full command you are trying to run. Unless
it's /u01/app/Dev/Informatica/GALAXY_INFA_HOME/server/bin/pmrep run -o
informatica_s, which likely means you are missing the input file.


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by leosraj** [comment]
The core file was owned by ucdprod (which is the id our UCD agent uses), so this is definitely through the plugin. The logs themselves don’t give any errors, but it ends abruptly. The portion of the command that shows is what shows in gdb from the core dump, which I think is just a truncated version of the real command, since the real command shown appears in the log. I can send the core file as well if desired.

From: Leo Selvaraj [mailto:leosraj@us.ibm.com]
Sent: Wednesday, December 06, 2017 2:53 PM
To: MENEGHELLO, JOSHUA A <j.meneghello@nationwide.com>
Cc: Author <author@noreply.github.com>; IBM-UrbanCode/Informatica-UCD <Informatica-UCD@noreply.github.com>; IBM-UrbanCode/Informatica-UCD <reply@reply.github.com>; Andres, Matthew (Matt) <ANDREM6@nationwide.com>
Subject: [EXTERNAL] Re: [IBM-UrbanCode/Informatica-UCD] When Importing multiple ImportObject, the program is terminating (#36)

Nationwide Information Security Warning: This is an external email. Do not click on links or open attachments unless you trust the sender.
________________________________


Josh,

Can you please email the logs to Nick by responding to this email.

Thanks.

LEO J. SELVARAJ
IBM Certified IT Specialist – Level Two
IBM Systems Middleware Services

________________________________

[2D barcode - encoded with contact information]

Phone: 1-720-395-1729 | Mobile: 1-248-837-9233
E-mail: leosraj@us.ibm.com<mailto:leosraj@us.ibm.com>
ISSW: www.ibm.com/developerworks/websphere/services/<http://www.ibm.com/developerworks/websphere/services/>

[cid:image002.jpg@01D36EA2.8DBA23E0]




[Inactive hide details for Nick Mathison ---12/06/2017 02:31:49 PM---Are you receiving this issue through the plugin or manual c]Nick Mathison ---12/06/2017 02:31:49 PM---Are you receiving this issue through the plugin or manual calls? If via plugin, would you mind post

**Comment by nhmathis** [comment]
Does that command work if run manually on the agent host?

**Comment by menegj1** [comment]
When using pmrep run, using the exact XMLs and control files generated by the UCD deployment, it doesn't work, and ends up with a memory dump, seen as follows:

pwcdevl@ehplavcs2091-DEV $ /u01/app/Dev/Informatica/pwc961hf2/server/bin/pmrep run -o informatica_script.1512668181345.out -f informatica_script.1512668181345.in

Informatica(r) PMREP, version [9.6.1 HotFix3], build [990.0611], LINUX 64-bit
Copyright (c) Informatica Corporation 1994 - 2015
All Rights Reserved.
This Software is protected by U.S. Patent Numbers 5,794,246; 6,014,670; 6,016,501; 6,029,178; 6,032,158; 6,035,307; 6,044,374; 6,092,086; 6,208,990; 6,339,775; 6,640,226; 6,789,096; 6,823,373; 6,850,947; 6,895,471; 7,117,215; 7,162,643; 7,243,110; 7,254,590; 7,281,001; 7,421,458; 7,496,588; 7,523,121; 7,584,422; 7,676,516; 7,720,842; 7,721,270; 7,774,791; 8,065,266; 8,150,803; 8,166,048; 8,166,071; 8,200,622; 8,224,873; 8,271,477; 8,327,419; 8,386,435; 8,392,460; 8,453,159; 8,458,230; 8,707,336; 8,886,617; and RE44,478, International Patents and other Patents Pending.

Invoked at Fri Dec 08 16:47:12 2017

Memory fault(coredump)

However, when taking the input file and appending pmrep infront of each of the commands and running it through a shell script, this works. I've attached the input file, script, and the outputs of each to this comment. I believe that the core dump is happening only because of using pmrep run.

[pmrepOutput.txt](https://github.com/IBM-UrbanCode/Informatica-UCD/files/1543910/pmrepOutput.txt)
[informatica_script.1512668181345input.txt](https://github.com/IBM-UrbanCode/Informatica-UCD/files/1543991/informatica_script.1512668181345input.txt)
[informatica_script.1512668181345out.txt](https://github.com/IBM-UrbanCode/Informatica-UCD/files/1543992/informatica_script.1512668181345out.txt)
[pmrepShell.txt](https://github.com/IBM-UrbanCode/Informatica-UCD/files/1543993/pmrepShell.txt)

**Comment by nhmathis** [comment]
Thank you! Few more questions...

In the above `pmrep run` error, was this command run manually or through UCD? Therefore, you are showing that we are getting the same error in UCD and manually? If it's failing manually, then it's likely an issue that should be raised with the Informatica support team.

For your manual tests, did you run them on the agent's host server? 

Can you run that same `pmrepShell.txt` script in a plugin `Shell` step? Does it succeed there as well?

**Comment by menegj1** [comment]
The pmrep run error is occurring in both places. I was able to get more information about why it was failing after running it manually, which shows the core dump, where as the log in UCD just ends abruptly. I've created an Informatica Support ticket as well, just to get both views on this point. And I did run it on the host server. This is occurring in all of our servers we have as UCD agents however, any time there are a large amount of xmls.

I'll see if I can get our UCD Admin to create a plugin Shell step using the steps I have in pmrepShell.txt and I will let you know the results.

**Comment by nhmathis** [comment]
From our general debugging steps, if we can't get it working manually, then it's not going to work through a plugin or shell step. The progression generally goes Manual -> Shell Step -> Final Plugin step. 

If it's failing manually, then going through Informatica support is likely the best action. The size of the .xml's causing an issue is a reasonable explanation on why the `pmrep` command is failing. These xml files are likely sufficient for their support.

**Comment by menegj1** [comment]
After working with Informatica, I may follow up with this. I think possibly something that could be added is that if pmrep returns with a specific error code, maybe something could be appended to the log, because the log in UCD gives no record of a crash occurring.

**Comment by suranc** [comment]
I didn't notice there was an issue opened for this, but I have opened pull request #37 which should resolve this issue.  I modified import_objects.groovy to generate a series of pmrep commands in a shell script.

**Comment by nhmathis** [comment]
Thank you!

**Comment by nhmathis** [comment]
Resolved and released in version 29.
