### ISSUE TITLE
Selecting the security domain for connection string on Import Objects.

### ISSUE THREAD

**Issue by jsarnovsky** [IBM-UrbanCode/Informatica-UCD#4]
UrbanCode Deploy 6.2.1 
Informatica plugin version 15 
Informatica(r) PMREP, version [9.6.1 HotFix3], LINUX 64-bit 
Description: Requesting ability to select the Security Domain as a variable as part of the Import Objects plugin in the connection string. This is the -s option for pmrep command connection. 

Error log: connect -r [repo] -n [userid] -x [pass] -d [domain] 
[UM_10007] [UM_10007] The user [userid] in security domain [Native] does not exist in the domain. [FAULT_PCSFINTERNALEXCEPTION] Repository connection failed. Failed to execute connect.

**Comment by nhmathis** [comment]
Issue has been resolved in version 17.
